### ISSUE TITLE
New excessive permissions?

### ISSUE THREAD

**Issue by SLCH** [kurtextrem/Layoutify-for-Instagram#105]
Got this popup

<details>
<summary>Screenshot</summary>

![Screenshot_20210922_170006](https://user-images.githubusercontent.com/2884941/134348337-63f8bed4-e746-4bc5-838f-8afd8c0af10b.png)

</details>

Not sure if this was intended.

My machine:
Chrome Version 93.0.4577.63 (Official Build) (64-bit)
Linux

**Comment by kurtextrem** [comment]
Damn, that was definitely not intended :(
I upgraded to Manifest V3 (latest version of the chrome manifest) and on dev mode I can't see the upgrade popups.....

**Comment by kurtextrem** [comment]
Fixed with https://github.com/kurtextrem/Layoutify-for-Instagram/commit/1397e814e2e26db334215150dfb89d3ad322d8de hopefully. Thank you for opening this issue so fast, let's hope I can prevent further damage fast enough.

**Comment by SLCH** [comment]
No problem :heart: 

Still waiting for that update to hit the store though :eyes:

**Comment by kurtextrem** [comment]
Yup, Google has to review it. I hope Manifest v3 leads to fast reviewing.

**Comment by SLCH** [comment]
`3.8.0` is here, but the permission stayed the same :eyes:

**Comment by kurtextrem** [comment]
cc https://github.com/kurtextrem/Layoutify-for-Instagram/issues/106

So I think what happened here is, Chrome is now showing this warning since I replaced webRequestBlocking with declarativeNetRequest, the documentation can be found here: developer.chrome.com/docs/extensions/reference/declarativeNetRequest

The chrome.declarativeNetRequest API is used to block or modify network requests by specifying declarative rules. This lets extensions modify network requests without intercepting them and viewing their content, thus providing more privacy.

Continuing:

Extensions must declare either the declarativeNetRequest or the declarativeNetRequestWithHostAccess (available since Chrome 96) permission in the extension manifest to use this API. The former (declarativeNetRequest) allows extensions to block and upgrade requests without any host permissions. Host permissions are still required if the extension wants to redirect a request or modify headers on it. The declarativeNetRequestWithHostAccess permission always requires host permissions to the request URL and initiator to act on a request."

Chrome Stable is on Chrome 94, so I can't use declarativeNetRequestWithHostAccess which only gives access to the permissions declared in the manifest -> So I fucked up there by updating too early (I'm on Chrome v96).
However, since I need to modify headers, the extension can only change: instagram.com, fbcdn.net (to display images), cdninstagram.com (to display images) - you can check that by right-clicking the extension -> "Manage extensions" and even turn off permissions.
There is no such thing as blocking or upgrading requests in this extension, these are the only rules: 7f99174#diff-e38ba45c4773d55aef8027c9be2b88f8aa5a33160964205a5b87194f564a123fR413

**Comment by kurtextrem** [comment]
https://github.com/kurtextrem/Layoutify-for-Instagram/blob/master/CHANGELOG.md#380---2021-09-22 changelog updated
