### ISSUE TITLE
request: documentation on new permission to block content

### ISSUE THREAD

**Issue by vike2000** [kurtextrem/Layoutify-for-Instagram#106]
Recently my Chrome (93.0.4577.63) disabled Layoutify, asking me to accept new permission to "Block content on any page that you visit".

![Screen Shot 2021-09-23 at 16 25 00](https://user-images.githubusercontent.com/821191/134737127-c103601b-f0f9-4cc9-af46-376bdb9b697e.png)

I did a quick web search and found this git repo (apart from the recurring problem of IG blocking people - 
I've had my share of temporary ones), but I was hoping to see an explanation to the new permission in [CHANGELOG.md](https://github.com/kurtextrem/Layoutify-for-Instagram/blob/master/CHANGELOG.md).
**Request**: Can you please add something there, and/or in the "Overview" text of the [chrome.google.com/webstore](https://chrome.google.com/webstore/detail/layoutify-improved-layout/nekeeojpcbiehcignddhindbgacbghmi?hl=en) entry.

Minor research: Manually searching the GitHub commits for "block", I find a removal of `"webRequestBlocking"` in `"permissions"` of [`manifest.json` in commit -m "move to manifest v3" # 7f99174](https://github.com/kurtextrem/Layoutify-for-Instagram/commit/7f99174d3dd806c2b64644ed37e32f4996f52c0e#diff-6bc2c0b5164076a1b57b067398be19a40d2b8efa3428b03504562ea88593866cL36) and nothing in the commits between that and current HEAD.
That is, I only find the inverse of adding a permission to block.

Thanks for all your work Jacob.

**Comment by kurtextrem** [comment]
So I think what happened here is, Chrome is now showing this warning since I replaced `webRequestBlocking` with `declarativeNetRequest`, the documentation can be found here: https://developer.chrome.com/docs/extensions/reference/declarativeNetRequest/ - "The chrome.declarativeNetRequest API is used to block or modify network requests by specifying declarative rules. This lets extensions modify network requests **without intercepting them and viewing their content, thus providing more privacy.**"

Continuing:
"Extensions must declare either the declarativeNetRequest or the declarativeNetRequestWithHostAccess (**available since Chrome 96**) permission in the extension manifest to use this API. The former (declarativeNetRequest ) allows extensions to block and upgrade requests without any host permissions. Host permissions are still required if the extension wants to redirect a request or modify headers on it. The declarativeNetRequestWithHostAccess permission always requires host permissions to the request URL and initiator to act on a request."

Chrome Stable is on Chrome 94, so I can't use `declarativeNetRequestWithHostAccess` which only gives access to the permissions declared in the manifest -> So I fucked up there by updating too early (I'm on Chrome v96). 
However, since I need to modify headers, the extension can only change: instagram.com, fbcdn.net (to display images), cdninstagram.com (to display images) - you can check that by right-clicking the extension -> "Manage extensions" and even turn off permissions.
There is no such thing as blocking or upgrading requests in this extension, these are the only rules: https://github.com/kurtextrem/Layoutify-for-Instagram/commit/7f99174d3dd806c2b64644ed37e32f4996f52c0e#diff-e38ba45c4773d55aef8027c9be2b88f8aa5a33160964205a5b87194f564a123fR413

**Comment by kurtextrem** [comment]
https://github.com/kurtextrem/Layoutify-for-Instagram/blob/master/CHANGELOG.md#380---2021-09-22 changelog updated

**Comment by vike2000** [comment]
Thank you very much for the details on APIs and versions. I'm satisfied and also hope it, along with #105, can help minimising unnecessary suspicions :)
