### ISSUE TITLE
I can no longer view the posts i've like with the extension 

### ISSUE THREAD

**Issue by Jsunshine013** [kurtextrem/Layoutify-for-Instagram#97]
The photos and videos arent showing up any more and im not sure if its something im doing wrong

**Comment by kurtextrem** [comment]
Hi @Jsunshine013, is this still happening with the latest version?

**Comment by googlephonics** [comment]
Hi there! Piggybacking on this. I can't see my Liked posts anymore. Latest version of Chrome, latest of the extension (from the Chrome store, unless there's another way to get a newer version?
![Screen Shot 2021-05-24 at 11 50 06](https://user-images.githubusercontent.com/47451822/119330236-4a1d3600-bc86-11eb-99f7-291b032d6acc.png)

**Comment by googlephonics** [comment]
Amazing extension, btw. Thanks for your hard work.

**Comment by kurtextrem** [comment]
Hi @googlephonics is this still happening if you clear the data (on the About page, the button). If yes, can you right click the image and copy & paste the url into here? So I can see what is happening.

A little background, and also why I had to request more permissions on the update before the last update: Instagram changed something regarding their servers, so that other websites apart from Instagram can't display them.

**Comment by googlephonics** [comment]
Hey, thanks for your reply. I just cleared the data and the issue persists. I figured IG had changed something on their side. This is the URL of one of the images: 

https://scontent-ber1-1.cdninstagram.com/v/t51.2885-15/e35/s1080x1080/189644053_298440402004074_4156485670102797930_n.jpg?tp=1&_nc_ht=scontent-ber1-1.cdninstagram.com&_nc_cat=106&_nc_ohc=Qm4UJ1sONsUAX9JBBXJ&edm=APv5SkIBAAAA&ccb=7-4&oh=b923c6fd22f402dea882efb0b53422e5&oe=60B25C3C&_nc_sid=7479f6&ig_cache_key=MjU4MDA5MzI1NDA0MTQzMDA4OQ%3D%3D.2-ccb7-4

**Comment by kurtextrem** [comment]
Thank you. Apparently they now redirect from the Facebook Image CDN to the Instagram CDN, which was not happening before. This unfortunately means, once again everyone will have to allow the permission after the update :(

Let's see if I can find any other workaround. I don't want to use a proxy, because that would mean potentially private photos hit the server and my principle is, what the user sees on their machine, stays on their machine. Always, privacy first.

**Comment by googlephonics** [comment]
Completely agree. Thanks for looking into it!

**Comment by kurtextrem** [comment]
Will be fixed with version 3.4.0, might be out today in a few hours.

**Comment by googlephonics** [comment]
Whoa, amazing! Thanks again.

**Comment by trodiz** [comment]
I think you have to manually go to the extensions page (chrome://extensions/) and check the permissions to make it work. Sometimes chrome doesn't prompt users for new permissions.

![Capture](https://user-images.githubusercontent.com/59777673/119456328-33471400-bd58-11eb-8f39-e9a33260ac8a.PNG)

**Comment by googlephonics** [comment]
I opened Chrome today and got the prompt that it had disabled the extension bc new permissions were required. It now works perfectly as before! Thank you again.

**Comment by kurtextrem** [comment]
@googlephonics Glad to hear, thank you!
